### ISSUE TITLE
wrong content encoding/decoding or problem with gzip encoded content

### ISSUE THREAD

**Issue by domsie** [Athlon1600/php-proxy#63]
https://fr.unblockvideos.com/index.php?q=nNeoodZukmijnZ-brNibo1_N06al25nHn6WSp2Sb0tBj1ZmYzKfXnqNncWlym29nYZ6Ya26Va55qbGdm

![image](https://cloud.githubusercontent.com/assets/16717242/26716278/189608f4-4779-11e7-95e6-fc5119240eb5.png)

**Comment by Athlon1600** [comment]
I need to know the exact page where this happens. That register.gotowebminar... URL throws 404 not found error for me.

**Comment by domsie** [comment]
Then use only https://register.gotowebinar.com as url

**Comment by Athlon1600** [comment]
It appears to me that this problem is unique to gotowebinar.com because it refuses to serve plain-text even if you explicitly ask for it.
An easy fix for that is to just tell cURL instance that php-proxy is using, to always request and deal with GZIP type responses. You can do that by adding this option into your php-proxy's config.php file:  
  
```php
$config['curl'] = array(
	CURLOPT_ENCODING => 'gzip'
);
```
