### ISSUE TITLE
Pre-installed version and gmail

### ISSUE THREAD

**Issue by AlMasterson** [Athlon1600/php-proxy#64]
Hi,
I installed the "pre-installed" version of the proxy, downloaded at www.php-proxy.com/download/php-proxy.zip, on my shared hosting. I tried using it to logon to gmail.com and when I try to push the "next" button after inserting my email address, nothing happens, as if it was not submitting the form.

Is this a bug or am I missing something in my installation, like an extra plugin or something, if so, what should I install and how.

Thank you

PS: Great script BTW

**Comment by lleevveell66** [comment]
Same problem, for me.  Every blank accepts text, then re-blanks out, again, when I click off.  But, if I click back on, each blank retains the text I entered.  

And, [Next] and "Sign in instead" ... all links do nothing.

Tried latest FF and Chrome.

Is no one else complaining because they've installed it the other way?  This seems like a big show stopper, and the issue is 3 years old.

**Comment by Athlon1600** [comment]
gmail.com is just too complicated of a site to "proxify". It depends on javascript too much, and php-proxy is not good at dealing with javascript. Same issue with many other sites. For that, you'll have to go outside php-proxy and use a real proxy server or something
https://www.proxynova.com/proxy-software/
