### ISSUE TITLE
Enabling Javascript for specific websites

### ISSUE THREAD

**Issue by schlarmanorg** [Athlon1600/php-proxy#94]
So say I only want JavaScript to work on Google or maybe Reddit, I have tried this:
`$config['js_remove'] = array(
	'twitter.com', 'reddit.com', 'youtube.com', 'www.google.com'
);
`
In the Config.php file. It doesn't seem to do anything at all.

**Comment by Athlon1600** [comment]
Javascript is enabled by default on ALL sites. The reason javascript is not working for you on reddit for example, is because reddit is probably too complex to "proxify" so scripting will be functioning properly on such sites. You would need to check your browser's developer console to see what's happening.
